/**
 * ComponentMigrator Basic Tests
 * Auto-generated by Web4TSComponent
 */

import { describe, it, expect } from 'vitest';
import { DefaultComponentMigrator } from '../src/ts/layer2/DefaultComponentMigrator.js';
import { execSync } from 'child_process';
import { existsSync } from 'fs';
import * as path from 'path';

describe('ComponentMigrator Basic Tests', () => {
  it('should create instance successfully', () => {
    const component = new DefaultComponentMigrator();
    expect(component).toBeDefined();
  });

  it('should have empty constructor (Web4 standard)', () => {
    const component = new DefaultComponentMigrator();
    expect(component).toBeInstanceOf(DefaultComponentMigrator);
  });
});

describe('ComponentMigrator CLI Location Resilience', () => {
  it('should work when called from scripts/ directory', () => {
    // Find project root ONCE by walking up from test file location
    // This MUST match the logic in DefaultWeb4TSComponent.findProjectRootFrom()
    const findProjectRoot = (startDir: string): string => {
      let currentDir = path.resolve(startDir);
      
      // First priority: Look for package.json + components/ directory
      // This is MORE SPECIFIC and will correctly identify test/data or project root
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, 'package.json')) &&
            existsSync(path.join(currentDir, 'components'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      
      // Fallback: Look for .git (for projects without components/ dir)
      currentDir = path.resolve(startDir);
      while (currentDir !== path.dirname(currentDir)) {
        if (existsSync(path.join(currentDir, '.git'))) {
          return currentDir;
        }
        currentDir = path.dirname(currentDir);
      }
      
      return path.resolve(startDir);
    };
    
    // Discover project root once, then use absolute paths everywhere
    const projectRoot = findProjectRoot(__dirname);
    const scriptsDir = path.join(projectRoot, 'scripts');
    const cliScriptPath = path.join(scriptsDir, 'componentmigrator');
    
    // Verify CLI script symlink exists in scripts/
    expect(existsSync(cliScriptPath)).toBe(true);
    
    // Test: Run CLI from scripts/ directory
    // This verifies location-resilient symlink resolution works correctly
    try {
      const result = execSync('./componentmigrator', {
        cwd: scriptsDir,
        encoding: 'utf-8',
        timeout: 10000
      });
      
      expect(result).toContain('ComponentMigrator CLI Tool');
      console.log('   ✅ CLI works from scripts/ directory (location-resilient)');
    } catch (error: any) {
      console.error('   ❌ CLI FAILED from scripts/ directory');
      console.error('   Error:', error.message);
      console.error('\n🔴 BUG: CLI script is NOT location-resilient!');
      console.error('   The CLI script needs proper symlink resolution logic.');
      throw new Error(`CLI script failed from scripts/ directory: ${error.message}`);
    }
  });
});
