/**
 * MessageTypes — Single source of truth for all WebSocket message types
 * Used by server and client. DRY — no hardcoded strings.
 */

export const MSG = {
  // Client → Server
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  LIST_ROOMS: 'LIST_ROOMS',
  START_GAME: 'START_GAME',
  PLAY_CARD: 'PLAY_CARD',
  PLAY_SPECIAL: 'PLAY_SPECIAL',
  ADD_BOT: 'ADD_BOT',
  GAME_STATE: 'GAME_STATE',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  SPECTATE: 'SPECTATE',
  SPECTATE_ROOM: 'SPECTATE_ROOM',
  LEAVE_SPECTATE: 'LEAVE_SPECTATE',
  JOIN_NEXT_GAME: 'JOIN_NEXT_GAME',

  // Server → Client
  ROOM_LIST: 'ROOM_LIST',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_LEFT: 'ROOM_LEFT',
  SERVER_CONFIG: 'SERVER_CONFIG',
  ERROR: 'ERROR',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  HOST_CHANGED: 'HOST_CHANGED',
  ROUND_START: 'ROUND_START',
  COUNTDOWN: 'COUNTDOWN',
  CARD_PLAYED: 'CARD_PLAYED',
  ROUND_RESULT: 'ROUND_RESULT',
  GAME_OVER: 'GAME_OVER',
  SPECIAL_CARD_PLAYED: 'SPECIAL_CARD_PLAYED',
  BOTS_FILLED: 'BOTS_FILLED',
  LOBBY_COUNTDOWN: 'LOBBY_COUNTDOWN',
  LOBBY_COUNTDOWN_CANCELLED: 'LOBBY_COUNTDOWN_CANCELLED',
  SPECTATE_JOINED: 'SPECTATE_JOINED',
  SPECTATE_LEFT: 'SPECTATE_LEFT',
  SPECTATOR_JOINED: 'SPECTATOR_JOINED',
  SPECTATOR_LEFT: 'SPECTATOR_LEFT',
  CHAT_HISTORY: 'CHAT_HISTORY',
  AUTO_START: 'AUTO_START',
} as const;

export type MessageType = typeof MSG[keyof typeof MSG];
